[package]
name = "chess-engine-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1.*"
lazy_static = "1.*"

[features]
default = []
cli-interface = []
uci = []
x_board = []
