[package]
name = "chess-engine-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1.*"
lazy_static = "1.*"
serde_json = "1.0.96"
rand = "0.8.5"
hex = "0.4.3"

[features]
default = []